const LIST_ALL = 'LIST_ALL';
const SAVE_TASK = 'SAVE_TASK'
const OPEN_FORM = 'OPEN_FORM';
const CLOSE_FORM = 'CLOSE_FORM'
const UPDATE_STATUS = 'UPDATE_STATUS'
const DELETE_TASK = 'DELETE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const FILTER_TABLE = 'FILTER_TABLE';
const SEARCH_NAME = 'SEARCH_NAME';
const ENTER_NAME = 'ENTER_NAME';
const SORT = 'SORT';

export { LIST_ALL, SAVE_TASK, OPEN_FORM, CLOSE_FORM, UPDATE_STATUS, DELETE_TASK, EDIT_TASK, FILTER_TABLE, SEARCH_NAME, ENTER_NAME, SORT };